version: '3'
services:
  ml_service:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      - ID_ACL_PUBLIC_SUBNET=${ID_ACL_PUBLIC_SUBNET}
      - IP_ELASTIC=${IP_ELASTIC}
      - PORT_ELASTIC=${PORT_ELASTIC}
    restart: always